[changelog]
header = """# Changelog

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/), this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html) and to [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/).

"""
body = """
{%- if version %}
## {{ version }} ({{ timestamp | date(format="%Y-%m-%d") }})
{%- endif %}
{%- for group, commits in commits | group_by(attribute="group") %}

### {{ group | upper_first }}
{%- for commit in commits %}
- {{ commit.message | upper_first }} [`{{ commit.id | truncate(length=7, end="") }}`](https://github.com/tomhoover/git-wt/commit/{{ commit.id }})
{%- endfor %}
{%- endfor %}
"""
trim   = true
footer = ""

[git]
conventional_commits  = true
filter_unconventional = true
split_commits         = false
tag_pattern           = "v[0-9].*"
sort_commits          = "oldest"
commit_parsers = [
  { message = "^chore: release", skip = true },
  { message = "^feat",           group = "Feature" },
  { message = "^fix",            group = "Bug Fixes" },
  { message = "^docs",           group = "Documentation" },
  { message = "^test",           group = "Test" },
  { message = "^refactor",       group = "Refactor" },
  { message = "^perf",           group = "Performance" },
  { message = "^ci",             group = "CI" },
  { message = "^chore",          group = "Chore" },
  { message = "^style",          group = "Style" },
  { message = "^revert",         group = "Revert" },
]
